/* eslint-disable */
// -----------------------------------------------------------------------------
// AUTO-GENERATED by scripts/gen-activities.mjs — shared builders + element type
// for the per-city activity catalogues in this folder. Do not edit by hand.
// -----------------------------------------------------------------------------
// Self-contained: imports nothing, mirrors the shape the hand-authored
// data/activities.data.ts uses, so core re-applies the Activity type on import.
export type Window = { open: number; close: number };
export const ALL_DAY: Window = { open: 0, close: 24 };
export const at = (open: number, close: number): Window => ({ open, close });
export const everyDay = (h: Window): Window[] => Array<Window>(7).fill(h);

export type CatalogueRestaurant = {
  type: "food" | "cafe";
  price: number | null;
  name: string;
  description: string;
  link: string | null;
  emoji: string | null;
};
export type CatalogueActivity = {
  id: number | null;
  name: string;
  description: string;
  hours: number;
  cost: number;
  coords: { lat: number; lng: number };
  program: Window[];
  cultural: number;
  foodie: number;
  adventurous: number;
  relaxing: number;
  priority: number;
  is_lunch?: boolean;
  prices: { ages: Record<string, number>; family: Record<string, number> } | null;
  websites: { url: string; name: string }[];
  googleMapUrl: string | null;
  notes: string[];
  tags: string[];
  best_time: string | null;
  restaurants: CatalogueRestaurant[];
  emoji: string | null;
};

export const food = (name: string, description: string, link: string | null): CatalogueRestaurant =>
  ({ type: "food", price: null, name, description, link, emoji: null });
export const cafe = (name: string, description: string, link: string | null): CatalogueRestaurant =>
  ({ type: "cafe", price: null, name, description, link, emoji: null });
export const site = (url: string, name = "Official site") => ({ url, name });
