/* eslint-disable */
// -----------------------------------------------------------------------------
// AUTO-GENERATED by scripts/gen-activities.mjs from the `images` of each
// takemytrip/data/<city>.json activity. Do not edit by hand — re-run the generator.
// -----------------------------------------------------------------------------
// EDITOR_ACTIVITY_IMAGES: activity ref ("<cityId>:<id>") -> images set in the
// editor. Remote images appear only with a complete credit.
// EDITOR_IMAGE_CREDITS: the credits the /credits page must list for them.
export type EditorImageCredit = {
  subject: string;
  author: string;
  license: string;
  licenseUrl: string;
  sourceUrl: string;
};

export const EDITOR_ACTIVITY_IMAGES: Record<string, string[]> = {

};

export const EDITOR_IMAGE_CREDITS: EditorImageCredit[] = [

];
