/* eslint-disable */
// -----------------------------------------------------------------------------
// AUTO-GENERATED by scripts/gen-activities.mjs — destination id -> its generated
// activity catalogue. Spread into ACTIVITIES_BY_DESTINATION in cities.data.ts.
// -----------------------------------------------------------------------------
import type { CatalogueActivity } from "./_helpers";
import { AMSTERDAM_ACTIVITIES } from "./amsterdam.data";
import { BARCELONA_ACTIVITIES } from "./barcelona.data";
import { BERLIN_ACTIVITIES } from "./berlin.data";
import { BUCHAREST_ACTIVITIES } from "./bucharest.data";
import { BUDAPEST_ACTIVITIES } from "./budapest.data";
import { ISTANBUL_ACTIVITIES } from "./istanbul.data";
import { KRAKOW_ACTIVITIES } from "./krakow.data";
import { LISBON_ACTIVITIES } from "./lisbon.data";
import { LONDON_ACTIVITIES } from "./london.data";
import { MADRID_ACTIVITIES } from "./madrid.data";
import { PARIS_ACTIVITIES } from "./paris.data";
import { PRAGUE_ACTIVITIES } from "./prague.data";
import { ROME_ACTIVITIES } from "./rome.data";
import { VIENNA_ACTIVITIES } from "./vienna.data";
import { WARSAW_ACTIVITIES } from "./warsaw.data";

export const GENERATED_ACTIVITIES_BY_DESTINATION: Record<string, CatalogueActivity[]> = {
  amsterdam: AMSTERDAM_ACTIVITIES,
  barcelona: BARCELONA_ACTIVITIES,
  berlin: BERLIN_ACTIVITIES,
  bucharest: BUCHAREST_ACTIVITIES,
  budapest: BUDAPEST_ACTIVITIES,
  istanbul: ISTANBUL_ACTIVITIES,
  krakow: KRAKOW_ACTIVITIES,
  lisbon: LISBON_ACTIVITIES,
  london: LONDON_ACTIVITIES,
  madrid: MADRID_ACTIVITIES,
  paris: PARIS_ACTIVITIES,
  prague: PRAGUE_ACTIVITIES,
  rome: ROME_ACTIVITIES,
  vienna: VIENNA_ACTIVITIES,
  warsaw: WARSAW_ACTIVITIES,
};
