-- AlterTable
ALTER TABLE "Image" ADD COLUMN     "cropHeight" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "cropWidth" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "cropX" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "cropY" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "flipHorizontal" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "flipVertical" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "scale" DOUBLE PRECISION NOT NULL DEFAULT 1;
