/* eslint-disable */
// -----------------------------------------------------------------------------
// AUTO-GENERATED by scripts/gen-activity-images.mjs — do not edit by hand.
// One local cover image per destination id (downloaded from CITY_IMAGES).
// -----------------------------------------------------------------------------
export const DESTINATION_IMAGES: Record<string, string> = {
  "amsterdam": "/destinations/amsterdam/cover.jpg",
  "barcelona": "/destinations/barcelona/cover.jpg",
  "berlin": "/destinations/berlin/cover.jpg",
  "bucharest": "/destinations/bucharest/cover.jpg",
  "budapest": "/destinations/budapest/cover.jpg",
  "istanbul": "/destinations/istanbul/cover.jpg",
  "krakow": "/destinations/krakow/cover.jpg",
  "lisbon": "/destinations/lisbon/cover.jpg",
  "london": "/destinations/london/cover.jpg",
  "madrid": "/destinations/madrid/cover.jpg",
  "paris": "/destinations/paris/cover.jpg",
  "prague": "/destinations/prague/cover.jpg",
  "rome": "/destinations/rome/cover.jpg",
  "vienna": "/destinations/vienna/cover.jpg",
  "warsaw": "/destinations/warsaw/cover.jpg",
};
