// scripts/photo-sync.lib.mjs
// -----------------------------------------------------------------------------
// Pure helpers for sync-photo-images.mjs. No filesystem, no sharp — unit-tested.
// -----------------------------------------------------------------------------
export const IMAGE_RE = /\.(avif|jpe?g|png|webp)$/i;

export function normalizeName(s) {
  return String(s)
    .normalize("NFC")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/[.\s]+$/g, "");
}

export function parseGeneratedMap(tsText) {
  const map = new Map();
  const re = /^\s*("(?:[^"\\]|\\.)*")\s*:\s*(\[[^\]]*\])\s*,?\s*$/gm;
  let m;
  while ((m = re.exec(tsText))) {
    map.set(JSON.parse(m[1]), JSON.parse(m[2]));
  }
  return map;
}

export function folderFromPath(p) {
  const m = String(p).match(/\/destinations\/([^/]+)\/([^/]+)\//);
  return m ? { id: m[1], folder: m[2] } : null;
}

export function pickSourceImage(entries) {
  return entries.filter((e) => IMAGE_RE.test(e)).sort()[0] || null;
}

// cityId (optional) scopes matching: activity names are NOT unique across
// cities (e.g. "Museum of Illusions" is in both krakow and warsaw), and the
// generated map is keyed by name alone — so a global match could grab the wrong
// city's folder. When cityId is given, only a map entry whose path is under that
// city counts; otherwise we fall through to the (already city-scoped) catalogue.
export function resolveTie(projName, generatedMap, catalogue, cityId) {
  const target = normalizeName(projName);
  for (const [name, paths] of generatedMap) {
    if (normalizeName(name) === target && paths[0]) {
      const fp = folderFromPath(paths[0]);
      if (fp && (!cityId || fp.id === cityId)) {
        return { name, id: fp.id, folder: fp.folder, inMap: true };
      }
    }
  }
  for (const a of catalogue) {
    if (normalizeName(a.name) === target && (!cityId || a.cityId === cityId)) {
      return { name: a.name, id: a.cityId, folder: a.folder, inMap: false };
    }
  }
  return null;
}

export function emitGeneratedText(map) {
  const keys = [...map.keys()].sort();
  const body = keys
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map.get(k))},`)
    .join("\n");
  return (
    `/* eslint-disable */\n` +
    `// -----------------------------------------------------------------------------\n` +
    `// AUTO-GENERATED by scripts/gen-activity-images.mjs — do not edit by hand.\n` +
    `// Maps activity name -> public-folder image paths (priority-weighted count).\n` +
    `// Re-run: \`node scripts/gen-activity-images.mjs\` (optionally \`--city=<id>\`).\n` +
    `// -----------------------------------------------------------------------------\n` +
    `export const GENERATED_ACTIVITY_IMAGES: Record<string, string[]> = {\n${body}\n};\n`
  );
}
