-- AlterTable
ALTER TABLE "Image" ADD COLUMN     "blur" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "inText" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "objectFit" TEXT NOT NULL DEFAULT 'cover',
ADD COLUMN     "overlayColor" TEXT,
ADD COLUMN     "positionX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "positionY" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "rotate" INTEGER NOT NULL DEFAULT 0;
